package practicaarboles;

import javax.swing.JOptionPane;

/**
 *
 * @author julian.agudelo1
 * @author Daniela Ocampo
 */
public class Construir extends javax.swing.JFrame {

    /**
     * Creates new form Construir
     */
    Validacion v = new Validacion();
    private String hileraTemp = "(";
    int subArbol = 0;

    public Construir() {
        initComponents();
        v.validar(txtAtomo);
        v.limitarCantidad(txtAtomo, 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAtomo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnSubArbol = new javax.swing.JButton();
        btnTermina = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelHileraTemp = new javax.swing.JLabel();
        btnHermano = new javax.swing.JButton();
        btnTerminaSub = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAtomo.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        txtAtomo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAtomo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAtomoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setText("Ingrese Átomo");

        btnOk.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnSubArbol.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnSubArbol.setText("Sub Arbol");
        btnSubArbol.setEnabled(false);
        btnSubArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubArbolActionPerformed(evt);
            }
        });

        btnTermina.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnTermina.setText("Terminar Arbol");
        btnTermina.setEnabled(false);
        btnTermina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminaActionPerformed(evt);
            }
        });

        jLabel2.setText("(Sólo letras)");

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel3.setText("Lo que llevas hasta el momento:");

        labelHileraTemp.setAutoscrolls(true);

        btnHermano.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnHermano.setText("Hermano");
        btnHermano.setEnabled(false);
        btnHermano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHermanoActionPerformed(evt);
            }
        });

        btnTerminaSub.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnTerminaSub.setText("Terminar Sub-Árbol");
        btnTerminaSub.setEnabled(false);
        btnTerminaSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminaSubActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAtomo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelHileraTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnTerminaSub)
                                    .addComponent(btnHermano, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(btnTermina))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(btnSubArbol)))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSubArbol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHermano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTerminaSub, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(btnTermina)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(labelHileraTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAtomo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOk)
                        .addGap(127, 127, 127))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:

        if (txtAtomo.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Por favor Asegurate de ingresar un átomo", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            if (hileraTemp.length() == 1) {
                hileraTemp += txtAtomo.getText();
            } else {
                if(hileraTemp.contains(txtAtomo.getText())){
                    JOptionPane.showMessageDialog(null, "Dato ya existe! \n Ingrese otro dato", "Error!", JOptionPane.ERROR_MESSAGE);
                    txtAtomo.setText("");
                    return;
                }
                hileraTemp += txtAtomo.getText();
                btnHermano.setEnabled(true);
            }
            labelHileraTemp.setText(hileraTemp); // escribe hilera en el label.
            txtAtomo.setText("");
            btnTermina.setEnabled(true);
            btnSubArbol.setEnabled(true);
            btnOk.setEnabled(false);
            txtAtomo.setEnabled(false);
                    
            if (subArbol == 0) {
                btnTerminaSub.setEnabled(false);
            } else {
                btnTerminaSub.setEnabled(true);
            }

        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnSubArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubArbolActionPerformed
        // TODO add your handling code here:
        hileraTemp += txtAtomo.getText() + "(";
        subArbol = subArbol + 1;
        btnOk.setEnabled(true);
        txtAtomo.setEnabled(true);
        btnTermina.setEnabled(false);
        btnSubArbol.setEnabled(false);
        btnHermano.setEnabled(false);
        btnTerminaSub.setEnabled(false);

    }//GEN-LAST:event_btnSubArbolActionPerformed

    private void btnTerminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminaActionPerformed
        // TODO add your handling code here:
        for (int i = subArbol; i >= 0; i--) {
            hileraTemp += ")";
        }
        labelHileraTemp.setText(hileraTemp);
        btnOk.setEnabled(false);
        btnTermina.setEnabled(false);
        btnSubArbol.setEnabled(false);
        btnHermano.setEnabled(false);
        btnTerminaSub.setEnabled(false);
        txtAtomo.setEnabled(false);
        this.setVisible(false);
    }//GEN-LAST:event_btnTerminaActionPerformed

    private void btnHermanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHermanoActionPerformed
        // TODO add your handling code here:
        hileraTemp += txtAtomo.getText() + ",";
        btnOk.setEnabled(true);
        btnTermina.setEnabled(false);
        btnSubArbol.setEnabled(false);
        btnHermano.setEnabled(false);
        btnTerminaSub.setEnabled(false);
        txtAtomo.setEnabled(true);
    }//GEN-LAST:event_btnHermanoActionPerformed

    private void btnTerminaSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminaSubActionPerformed
        // TODO add your handling code here:

        hileraTemp += ")";
        subArbol = subArbol - 1;
        labelHileraTemp.setText(hileraTemp);
        btnOk.setEnabled(false);
        btnTermina.setEnabled(true);
        btnSubArbol.setEnabled(true);
        btnHermano.setEnabled(true);
        btnTerminaSub.setEnabled(true);
        if (subArbol == 0) {
            btnTerminaSub.setEnabled(false);
            btnHermano.setEnabled(false);
            btnSubArbol.setEnabled(false);
        }
    }//GEN-LAST:event_btnTerminaSubActionPerformed

    private void txtAtomoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAtomoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAtomoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Construir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Construir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Construir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Construir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Construir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHermano;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnSubArbol;
    private javax.swing.JButton btnTermina;
    private javax.swing.JButton btnTerminaSub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelHileraTemp;
    private javax.swing.JTextField txtAtomo;
    // End of variables declaration//GEN-END:variables

    public String getHileraTemp() {
        return hileraTemp;
    }
}
