/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaarboles;

import javax.swing.JOptionPane;

/**
 *
 * @author julian.agudelo1
 * @author Daniela Ocampo
 */
public class Opciones extends javax.swing.JFrame {

    Validacion v = new Validacion();
    Construir c = new Construir();
    ListaGeneralizada arbol = new ListaGeneralizada();
    private ListaLigada arbolBinario = new ListaLigada();

    /**
     * Creates new form Opciones
     */
    public Opciones() {
        initComponents();
        v.validar(txtAtomoInteresado);
        v.limitarCantidad(txtAtomoInteresado, 1);
        panelRecorridos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnImprime = new javax.swing.JButton();
        btnAltura = new javax.swing.JButton();
        btnGradoArbol = new javax.swing.JButton();
        btnNArioBinario = new javax.swing.JButton();
        btnHojas = new javax.swing.JButton();
        btnAncestros = new javax.swing.JButton();
        btnRecorridos = new javax.swing.JButton();
        txtAtomoInteresado = new javax.swing.JTextField();
        btnGradoAtomo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnConstruir = new javax.swing.JButton();
        panelRecorridos = new javax.swing.JPanel();
        btnIn = new javax.swing.JButton();
        btnPre = new javax.swing.JButton();
        btnPos = new javax.swing.JButton();
        btnNiveles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setText("¿Qué desea hacer?");

        btnImprime.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnImprime.setText("Imprimir Árbol");
        btnImprime.setEnabled(false);
        btnImprime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimeActionPerformed(evt);
            }
        });

        btnAltura.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnAltura.setText("Altura");
        btnAltura.setEnabled(false);
        btnAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlturaActionPerformed(evt);
            }
        });

        btnGradoArbol.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnGradoArbol.setText("Grado del árbol");
        btnGradoArbol.setEnabled(false);
        btnGradoArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradoArbolActionPerformed(evt);
            }
        });

        btnNArioBinario.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnNArioBinario.setText("Convertir a árbol binario");
        btnNArioBinario.setEnabled(false);
        btnNArioBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNArioBinarioActionPerformed(evt);
            }
        });

        btnHojas.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnHojas.setText("Número de hojas");
        btnHojas.setEnabled(false);
        btnHojas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHojasActionPerformed(evt);
            }
        });

        btnAncestros.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnAncestros.setText("Ancestros");
        btnAncestros.setEnabled(false);
        btnAncestros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAncestrosActionPerformed(evt);
            }
        });

        btnRecorridos.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnRecorridos.setText("Recorridos");
        btnRecorridos.setEnabled(false);
        btnRecorridos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecorridosActionPerformed(evt);
            }
        });

        txtAtomoInteresado.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        txtAtomoInteresado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAtomoInteresado.setEnabled(false);
        txtAtomoInteresado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAtomoInteresadoActionPerformed(evt);
            }
        });

        btnGradoAtomo.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnGradoAtomo.setText("Grado");
        btnGradoAtomo.setEnabled(false);
        btnGradoAtomo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradoAtomoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel2.setText("Ingrese átomo");

        btnConstruir.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnConstruir.setText("Construir Arbol");
        btnConstruir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConstruirActionPerformed(evt);
            }
        });

        btnIn.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnIn.setText("In-orden");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        btnPre.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnPre.setText("Pre-orden");
        btnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreActionPerformed(evt);
            }
        });

        btnPos.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnPos.setText("Pos-orden");
        btnPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosActionPerformed(evt);
            }
        });

        btnNiveles.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnNiveles.setText("Por niveles");
        btnNiveles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivelesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRecorridosLayout = new javax.swing.GroupLayout(panelRecorridos);
        panelRecorridos.setLayout(panelRecorridosLayout);
        panelRecorridosLayout.setHorizontalGroup(
            panelRecorridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecorridosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelRecorridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPos)
                    .addComponent(btnIn))
                .addGap(18, 18, 18)
                .addGroup(panelRecorridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPre)
                    .addComponent(btnNiveles))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRecorridosLayout.setVerticalGroup(
            panelRecorridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecorridosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRecorridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIn)
                    .addComponent(btnPre))
                .addGap(18, 18, 18)
                .addGroup(panelRecorridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPos)
                    .addComponent(btnNiveles))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNArioBinario)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(btnAltura))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnHojas)
                                    .addComponent(btnGradoArbol)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(btnRecorridos))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnConstruir)
                                    .addComponent(btnImprime))))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnGradoAtomo))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtAtomoInteresado, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(144, 144, 144))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnAncestros)
                                    .addGap(136, 136, 136)))
                            .addComponent(panelRecorridos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(120, 120, 120))))
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnConstruir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtAtomoInteresado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAncestros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGradoAtomo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelRecorridos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnNArioBinario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGradoArbol)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAltura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnHojas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRecorridos))
                            .addComponent(btnImprime))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimeActionPerformed
        // TODO add your handling code here:
        arbol.ConstruyeArbol(c.getHileraTemp());
        btnNArioBinario.setEnabled(true);
        JOptionPane.showMessageDialog(null, arbol.imprimeArbol(arbol.getPrimero(), 0), "Hilera que representa el árbol n-ario", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnImprimeActionPerformed

    private void btnConstruirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConstruirActionPerformed
        // TODO add your handling code here:
        c.setVisible(true);
        btnConstruir.setEnabled(false);
        btnImprime.setEnabled(true);
    }//GEN-LAST:event_btnConstruirActionPerformed

    private void btnNArioBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNArioBinarioActionPerformed
        // TODO add your handling code here:
        arbolBinario.convierteLgABinario(arbol);
        JOptionPane.showMessageDialog(null, "Transformación satisfactoria", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        btnNArioBinario.setEnabled(false);
        btnAltura.setEnabled(true);
        btnAncestros.setEnabled(true);
        btnGradoArbol.setEnabled(true);
        btnGradoAtomo.setEnabled(true);
        btnHojas.setEnabled(true);
        btnRecorridos.setEnabled(true);
        txtAtomoInteresado.setEnabled(true);
    }//GEN-LAST:event_btnNArioBinarioActionPerformed

    private void btnGradoArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradoArbolActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, arbolBinario.gradoNArioEnBinario(arbolBinario.getPrimero()), "Grado del árbol n-ario", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnGradoArbolActionPerformed

    private void btnAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlturaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, arbolBinario.alturaNArioEnBinario(arbolBinario.getPrimero()), "Altura del árbol n-ario", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAlturaActionPerformed

    private void btnHojasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHojasActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, arbolBinario.hojasNArioEnBinario(arbolBinario.getPrimero()), "Número de hojas del árbol n-ario", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnHojasActionPerformed

    private void btnAncestrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAncestrosActionPerformed
        // TODO add your handling code here:
        if (txtAtomoInteresado.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Por favor Asegurate de ingresar un átomo", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            
            JOptionPane.showMessageDialog(null, arbolBinario.ancestrosNArioEnBinario(txtAtomoInteresado.getText().charAt(0)), "Ancestros de: " + txtAtomoInteresado.getText(), JOptionPane.INFORMATION_MESSAGE);
        }
        txtAtomoInteresado.setText("");
    }//GEN-LAST:event_btnAncestrosActionPerformed

    private void btnGradoAtomoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradoAtomoActionPerformed
        // TODO add your handling code here:
        if (txtAtomoInteresado.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Por favor Asegurate de ingresar un átomo", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            int grado = arbolBinario.gradoDato(txtAtomoInteresado.getText().charAt(0));
            if (grado == -1) {
                JOptionPane.showMessageDialog(null, "El dato ingresado no se encuentra en el árbol");
            } else {
                JOptionPane.showMessageDialog(null, grado, "El grado del dato: " + txtAtomoInteresado.getText().charAt(0), JOptionPane.INFORMATION_MESSAGE);
            }
        }
        txtAtomoInteresado.setText("");
    }//GEN-LAST:event_btnGradoAtomoActionPerformed

    private void btnRecorridosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecorridosActionPerformed
        // TODO add your handling code here:
        panelRecorridos.setVisible(true);
    }//GEN-LAST:event_btnRecorridosActionPerformed

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, arbolBinario.inorden(arbolBinario.getPrimero()), "Recorrido INORDEN del árbol", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnInActionPerformed

    private void btnPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, arbolBinario.posorden(arbolBinario.getPrimero()), "Recorrido POSORDEN del árbol", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnPosActionPerformed

    private void btnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, arbolBinario.preorden(arbolBinario.getPrimero()), "Recorrido PREORDEN del árbol", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnPreActionPerformed

    private void btnNivelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivelesActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, arbolBinario.recorridoPorNiveles(), "Recorrido por niveles del árbol n-ario:  ", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnNivelesActionPerformed

    private void txtAtomoInteresadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAtomoInteresadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAtomoInteresadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltura;
    private javax.swing.JButton btnAncestros;
    private javax.swing.JButton btnConstruir;
    private javax.swing.JButton btnGradoArbol;
    private javax.swing.JButton btnGradoAtomo;
    private javax.swing.JButton btnHojas;
    private javax.swing.JButton btnImprime;
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnNArioBinario;
    private javax.swing.JButton btnNiveles;
    private javax.swing.JButton btnPos;
    private javax.swing.JButton btnPre;
    private javax.swing.JButton btnRecorridos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelRecorridos;
    private javax.swing.JTextField txtAtomoInteresado;
    // End of variables declaration//GEN-END:variables

    public ListaLigada getArbolBinario() {
        return arbolBinario;
    }
}
